name: Build Packer on Push

on:
  push:
    branches:
      - main

jobs:
  build-packer:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Message
        run: echo "Push event detected on the main branch."

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true
          universe: googleapis.com
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          id_token_include_email: false

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: "latest"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Install modules
        run: npm install

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Packer init
        run: packer init ami.pkr.hcl

      - name: create and configure
        run: |
          touch .env
          echo DBPORT=${{ secrets.DBPORT }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DIALECT=${{ secrets.DIALECT }} >> .env
          echo DBUSER=${{ secrets.DBUSER }} >> .env
          echo DBPASSWORD=${{ secrets.DBPASSWORD }}>> .env
          echo DBNAME=${{ secrets.DBNAME }} >> .env

      - name: Build Artifact
        run: zip -r webapp.zip . -x ".git*" -x ".github*"

      - name: Publish Web App Artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: webapp.zip

      - name: check path
        run: |
          pwd
          ls /home/runner/work/webapp/webapp

      - name: Build Image on GCP
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE_FAMILY: "centos-stream-8"
          IMAGE_PROJECT: "centos-cloud"
          CUSTOM_IMAGE_FAMILY: "csye6225-custom-image-family"
          CUSTOM_IMAGE_NAME: "csye6225-custom-image"
          MACHINE_TYPE: "n1-standard-2"
          DISK_SIZE: "100"
          ZONE: "us-east1-b"
        run: |
          packer build -var "project_id=${PROJECT_ID}" -var "image_family=${IMAGE_FAMILY}" -var "image_project=${IMAGE_PROJECT}" \
                       -var "custom_image_family=${CUSTOM_IMAGE_FAMILY}" -var "custom_image_name=${CUSTOM_IMAGE_NAME}" \
                       -var "machine_type=${MACHINE_TYPE}" -var "disk_size=${DISK_SIZE}" -var "zone=${ZONE}" \
                       ami.pkr.hcl
