name: Integration Tests

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DBUSER }}
          POSTGRES_PASSWORD: ${{ secrets.DBPASSWORD }}
          POSTGRES_DB: ${{ secrets.DBNAME }}
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [16.x]
    env:
      PORT: ${{ secrets.PORT }}
      DBNAME: ${{ secrets.DBNAME }}
      DBUSER: ${{ secrets.DBUSER }}
      DBPASSWORD: ${{ secrets.DBPASSWORD }}
      DBPORT: ${{ secrets.DBPORT }}
      DIALECT: ${{ secrets.DIALECT }}
    steps:
      - uses: actions/checkout@v1
      - name: Capture PostgreSQL Container ID
        id: postgres-container
        run: echo "::set-output name=container_id::$(docker ps -q --filter "name=postgres")"
      - name: Display PostgreSQL Container Logs
        run: docker logs ${{ steps.postgres-container.outputs.container_id }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
